/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LancamentosIndexRouteImport } from './routes/lancamentos.index'
import { Route as LancamentosNovoRouteImport } from './routes/lancamentos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosIndexRoute = LancamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LancamentosRoute,
} as any)
const LancamentosNovoRoute = LancamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => LancamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/lancamentos': typeof LancamentosRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/lancamentos/novo': typeof LancamentosNovoRoute
  '/lancamentos/': typeof LancamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/relatorios': typeof RelatoriosRoute
  '/lancamentos/novo': typeof LancamentosNovoRoute
  '/lancamentos': typeof LancamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/lancamentos': typeof LancamentosRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/lancamentos/novo': typeof LancamentosNovoRoute
  '/lancamentos/': typeof LancamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/lancamentos'
    | '/relatorios'
    | '/lancamentos/novo'
    | '/lancamentos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajustes' | '/relatorios' | '/lancamentos/novo' | '/lancamentos'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/lancamentos'
    | '/relatorios'
    | '/lancamentos/novo'
    | '/lancamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  LancamentosRoute: typeof LancamentosRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos/': {
      id: '/lancamentos/'
      path: '/'
      fullPath: '/lancamentos/'
      preLoaderRoute: typeof LancamentosIndexRouteImport
      parentRoute: typeof LancamentosRoute
    }
    '/lancamentos/novo': {
      id: '/lancamentos/novo'
      path: '/novo'
      fullPath: '/lancamentos/novo'
      preLoaderRoute: typeof LancamentosNovoRouteImport
      parentRoute: typeof LancamentosRoute
    }
  }
}

interface LancamentosRouteChildren {
  LancamentosNovoRoute: typeof LancamentosNovoRoute
  LancamentosIndexRoute: typeof LancamentosIndexRoute
}

const LancamentosRouteChildren: LancamentosRouteChildren = {
  LancamentosNovoRoute: LancamentosNovoRoute,
  LancamentosIndexRoute: LancamentosIndexRoute,
}

const LancamentosRouteWithChildren = LancamentosRoute._addFileChildren(
  LancamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  LancamentosRoute: LancamentosRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
